"""Core domain contracts for Linkage Engine."""

from mapel_linkage.domain.errors import (
    AdjudicationError,
    AnchorBudgetExceeded,
    AnchorEvidenceError,
    AssignmentError,
    BoostedTreeBudgetExceeded,
    BoostedTreeError,
    CalibrationArtifactError,
    CalibrationError,
    CandidateBudgetExceeded,
    CandidateGenerationError,
    ClusteringError,
    ComparisonFeatureError,
    DataPlaneError,
    DecisionPolicyError,
    FellegiSunterBudgetExceeded,
    FellegiSunterError,
    LabelProvenanceError,
    LinkageRuntimeError,
    ModelSelectionError,
    PipelineError,
    PreprocessingError,
    RankingError,
    ValidationReportError,
)
from mapel_linkage.domain.table_refs import TableRef

__all__ = [
    "AdjudicationError",
    "AnchorBudgetExceeded",
    "AnchorEvidenceError",
    "AssignmentError",
    "BoostedTreeBudgetExceeded",
    "BoostedTreeError",
    "CalibrationArtifactError",
    "CalibrationError",
    "CandidateBudgetExceeded",
    "CandidateGenerationError",
    "ClusteringError",
    "ComparisonFeatureError",
    "DataPlaneError",
    "DecisionPolicyError",
    "FellegiSunterBudgetExceeded",
    "FellegiSunterError",
    "LabelProvenanceError",
    "LinkageRuntimeError",
    "ModelSelectionError",
    "PipelineError",
    "PreprocessingError",
    "RankingError",
    "TableRef",
    "ValidationReportError",
]
