"""Public benchmarking tools, contracts, runner, and seed corpus generation."""

from mapel_linkage.benchmarking.advisor_catalogue import (
    AdvisorCorpusDesignManifest,
    AdvisorCorpusReadinessManifest,
    BenchmarkShard,
    BenchmarkShardPlan,
    build_advisor_corpus_design,
    build_advisor_corpus_readiness,
    build_advisor_v2_generator,
    build_benchmark_shard_plan,
)
from mapel_linkage.benchmarking.advisor_execution import (
    CorpusExecutionApproval,
    CorpusShardExecutionReport,
    audit_advisor_corpus,
    execute_advisor_corpus_shard,
)
from mapel_linkage.benchmarking.advisor_v3_catalogue import (
    AdvisorV3CorpusDesignManifest,
    AdvisorV3CorpusReadinessManifest,
    AdvisorV3GeometryCoherenceManifest,
    AdvisorV3PreregistrationManifest,
    AdvisorV3ShardPlan,
    advisor_v3_family_roles,
    build_advisor_v3_corpus_design,
    build_advisor_v3_corpus_readiness,
    build_advisor_v3_generator,
    build_advisor_v3_geometry_coherence,
    build_advisor_v3_preregistration,
    build_advisor_v3_shard_plan,
    validate_advisor_v3_geometry_coherence,
)
from mapel_linkage.benchmarking.advisor_v3_execution import (
    AdvisorV3CorpusExecutionApproval,
    AdvisorV3GovernancePreparationReport,
    AdvisorV3ShardExecutionReport,
    advisor_v3_execution_provenance_digest,
    audit_advisor_v3_corpus,
    build_advisor_v3_execution_approval,
    execute_advisor_v3_corpus_shard,
    load_committed_advisor_v3_preregistration,
    prepare_advisor_v3_execution,
)
from mapel_linkage.benchmarking.advisor_v3_features import AdvisorV3MechanismProfile
from mapel_linkage.benchmarking.contracts import (
    BenchmarkAggregateMetrics,
    BenchmarkEvidenceScope,
    BenchmarkFailureRecord,
    BenchmarkRegistrySnapshot,
    BenchmarkRunRecord,
    BenchmarkRunStatus,
    CoverageSummaryReport,
    ScenarioFamilyManifest,
    ScenarioInstanceManifest,
)
from mapel_linkage.benchmarking.generator import (
    BenchmarkScenarioBundle,
    BenchmarkScenarioGenerator,
    ScenarioLatentSpec,
    ScenarioMechanicExtensionV3,
)
from mapel_linkage.benchmarking.registry import (
    BenchmarkRegistry,
    build_registry_snapshot,
)
from mapel_linkage.benchmarking.runner import (
    BenchmarkPortfolioRunner,
    BenchmarkRecipe,
    BenchmarkRunResult,
)
from mapel_linkage.benchmarking.seed_corpus import (
    generate_and_run_seed_corpus,
)

__all__ = [
    "AdvisorCorpusDesignManifest",
    "AdvisorCorpusReadinessManifest",
    "AdvisorV3CorpusDesignManifest",
    "AdvisorV3CorpusExecutionApproval",
    "AdvisorV3CorpusReadinessManifest",
    "AdvisorV3GeometryCoherenceManifest",
    "AdvisorV3GovernancePreparationReport",
    "AdvisorV3MechanismProfile",
    "AdvisorV3PreregistrationManifest",
    "AdvisorV3ShardExecutionReport",
    "AdvisorV3ShardPlan",
    "BenchmarkAggregateMetrics",
    "BenchmarkEvidenceScope",
    "BenchmarkFailureRecord",
    "BenchmarkPortfolioRunner",
    "BenchmarkRecipe",
    "BenchmarkRegistry",
    "BenchmarkRegistrySnapshot",
    "BenchmarkRunRecord",
    "BenchmarkRunResult",
    "BenchmarkRunStatus",
    "BenchmarkScenarioBundle",
    "BenchmarkScenarioGenerator",
    "BenchmarkShard",
    "BenchmarkShardPlan",
    "CorpusExecutionApproval",
    "CorpusShardExecutionReport",
    "CoverageSummaryReport",
    "ScenarioFamilyManifest",
    "ScenarioInstanceManifest",
    "ScenarioLatentSpec",
    "ScenarioMechanicExtensionV3",
    "advisor_v3_execution_provenance_digest",
    "advisor_v3_family_roles",
    "audit_advisor_corpus",
    "audit_advisor_v3_corpus",
    "build_advisor_corpus_design",
    "build_advisor_corpus_readiness",
    "build_advisor_v2_generator",
    "build_advisor_v3_corpus_design",
    "build_advisor_v3_corpus_readiness",
    "build_advisor_v3_execution_approval",
    "build_advisor_v3_generator",
    "build_advisor_v3_geometry_coherence",
    "build_advisor_v3_preregistration",
    "build_advisor_v3_shard_plan",
    "build_benchmark_shard_plan",
    "build_registry_snapshot",
    "execute_advisor_corpus_shard",
    "execute_advisor_v3_corpus_shard",
    "generate_and_run_seed_corpus",
    "load_committed_advisor_v3_preregistration",
    "prepare_advisor_v3_execution",
    "validate_advisor_v3_geometry_coherence",
]
