#!/usr/bin/env python3
"""Generate the repository SHA-256 manifest deterministically."""

from __future__ import annotations

import hashlib
from pathlib import Path

from verify_repository import MANIFEST_PATH, ROOT, candidate_files


def main() -> int:
    lines = [
        "# SHA-256 repository manifest",
        "# Generated by scripts/generate_repository_manifest.py; excludes this file itself.",
    ]
    for path in candidate_files():
        if path == MANIFEST_PATH:
            continue
        payload = path.read_bytes()
        relative = path.relative_to(ROOT)
        digest = hashlib.sha256(payload).hexdigest()
        lines.append(f"{digest}  {len(payload):8d}  {relative}")
    MANIFEST_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("Repository manifest generated.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
