#!/usr/bin/env python3
"""Generate the source-owned public error-code catalogue deterministically."""

from __future__ import annotations

import argparse
import re
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = ROOT / "src" / "mapel_linkage"
DESTINATION = ROOT / "docs" / "release" / "ERROR_CODE_CATALOGUE.md"
ERROR_CODE_PATTERN = re.compile(r"[\"'](ML-[A-Z0-9]+(?:-[A-Z0-9]+)+)[\"']")


def catalogue_markdown() -> str:
    owners: dict[str, set[str]] = defaultdict(set)
    for path in sorted(SOURCE_ROOT.rglob("*.py")):
        relative = str(path.relative_to(ROOT))
        text = path.read_text(encoding="utf-8")
        for code in ERROR_CODE_PATTERN.findall(text):
            owners[code].add(relative)

    lines = [
        "# Error Code Catalogue",
        "",
        "Generated by `scripts/generate_error_code_catalogue.py` from package-owned source",
        "literals. Codes are stable public diagnostics; arbitrary configuration values, paths,",
        "record values, identifiers, candidate pairs, and backend tracebacks are excluded.",
        "",
        "| Code | Owning source modules |",
        "|---|---|",
    ]
    lines.extend(
        f"| `{code}` | {', '.join(f'`{owner}`' for owner in sorted(code_owners))} |"
        for code, code_owners in sorted(owners.items())
    )
    lines.extend(
        [
            "",
            f"Catalogue count: **{len(owners)}** unique codes.",
            "",
            "A code identifies a safe failure class. It does not authorize exposing the rejected",
            "input, local path, configuration value, row, pair, model content, or secret.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = catalogue_markdown()
    if args.check:
        if not DESTINATION.is_file() or DESTINATION.read_text(encoding="utf-8") != expected:
            print("ERROR: The generated error-code catalogue is stale.")
            return 1
        print("Error-code catalogue verified.")
        return 0
    DESTINATION.parent.mkdir(parents=True, exist_ok=True)
    DESTINATION.write_text(expected, encoding="utf-8")
    print("Error-code catalogue generated.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
